### ISSUE TITLE
PostgreSQL incompatibility with AWS Redshift?

### ISSUE THREAD

**Issue by kylelundstedt** [SequoiaStudios/DB1#13]
I'm a big fan of the new DB1 package, but also a big user of Amazon Web Services' Redshift database.  I can connect to our Redshift cluster using the standard psql tool in the following way:

`psql -h our.server.com -U ourusername -d ourdatabasename -p 5439`

However, when I manually setup the same connection information in DB1:

```
{
  "stored_connections":
  {
    "ourusername@our.server.com":
    {
      "database_type": "PostgreSQL",
      "connection_name": "ourusername@our.server.com",
      "password": "ourpassword",
      "port": 5439,
      "connection_timeout": 5
    }
  },
}
```

I get a "timeout expired" error.  Is there something simple that I'm missing, or is there some kind of driver incompatibility or something?  Thanks!

**Comment by alexggordon** [comment]
Hey Kyle! I'm glad you enjoy it! 

There's nothing I can think of that would make DB1 incompatible with Redshift. Let me dig into it later today and I'll post back with the results!

**Comment by alexggordon** [comment]
@kylelundstedt so I went ahead and created my own Redshift cluster to test this out. It looks like I was able to connect just fine to my Redshift cluster, and execute queries. I did however find a bug in that when I connect to a PostgreSQL database. I immediately look for the default `postgres` database, which it appears Redshift has removed (Redshift is actually a fork of Postgres 8.1). Fortunately, I was able to fix it easily, as you can still execute queries in PostgreSQL without a database selected. 

I've fixed this bug, and it appears connecting to Redshift works perfectly fine now. I would however increase the "connection_timeout" to 15 or 20 seconds (`"connection_timeout": 15`). In ab5a5ad8717a2ddf6b2e8c15e9baa37e1a75fc22 I updated the documentation with some more clear items you can put in the settings. I also made it a little bit easier to connect to databases with custom ports, it that you can now just use the syntax `user@host:port` when running the `db1_connect` command. 

As soon as Package Control scrapes the new version I put up, you should be able to run `Package Control: Upgrade Package` and get the new version of DB1. Let me know if it works!

**Comment by alexggordon** [comment]
Key @kylelundstedt, just wanted to check in one last time. Is there still an issue?

**Comment by kylelundstedt** [comment]
Hi @alexggordon , still no joy.  After updating to DB1 v1.1.0, I tried connecting and got the following error:

```
DB1 Error: An error occured while connecting to the selected host.

FATAL:  database "masteruser" does not exist

Some additional information about the error is below.
  database: postgres
  host: mortgage.industryvault.com
  username: masteruser
  method: Postgresql.connect()
```

I'm befuddled by the error message.  My "Default.sublime-settings - User" file looks like:

```
{
    "stored_connections":
    {
        "masteruser@mortgage.industryvault.com":
        {
            "database_type": "PostgreSQL",
            "password": "xxx",
            "port": 5439,
            "connection_timeout": 20,
        }
    }
}
```

I've reconfirmed that the psql connections is still working.  Any ideas?

Thanks
Kyle

**Comment by kylelundstedt** [comment]
Hi @alexggordon!  Did my Nov 10th response make sense?  Let me know if there's anything else you need.

Thanks
Kyle

**Comment by blakeburch** [comment]
Hey @alexggordon. Just wanted to confirm that I'm running into the same issue as @kylelundstedt. Connecting to Redshift servers via PostgreSQL is resulting in an error that says "FATAL: database "myusername" does not exist".

Was really looking forward to using DB1 in sublime to replace my usage of SQL Workbench/J, but it doesn't look like that will be possible for now.

**Comment by mewwts** [comment]
Any news on this?

**Comment by dimon222** [comment]
I believe to resolve this issue is enough just add support of setting up custom database name to log in.
Psycopg2 directly supports it in [connector](http://initd.org/psycopg/docs/module.html#psycopg2.connect). The reason why it worked for @alexggordon is that he's using master user (literally - root), which might have same-called schema on cluster. If your user doesn't have one on cluster, you end up situation with exception.

I would fix it myself, but I guess this project is commercial, so all the package distribution is compiled C code in Package Control. Please add this feature, its a few minutes of work, but new customers for your plugin.
