### ISSUE TITLE
Can't connect to PostreSQL running on Vagrant machine

### ISSUE THREAD

**Issue by nkantar** [SequoiaStudios/DB1#16]
Trialling the plugin and would love to use it, but I can't seem to connect to PostgreSQL running on a Vagrant machine. Both the Django app and pgAdmin connect fine.

In the below snippets, "elevator" refers to the username. It seems like it's looking for a database with the same name. User config is empty, as I just installed the plugin using Package Control. Sublime Text 3 latest build on OS X (10.11.2, latest stable).

Address:

```
elevator@localhost:5432
```

Console output:

```
DB1 Error: An error occured while connecting to the selected host.

FATAL:  database "elevator" does not exist

Some additional information about the error is below.
  username: elevator
  host: localhost
  database: postgres
  method: Postgresql.connect()
```

Am I maybe just specifying the connection parameters wrong somehow?

**Comment by joshskidmore** [comment]
Seems like the same (or very similar) issue as [I'm having](https://github.com/SequoiaStudios/DB1/issues/15). I think this project is dead as I've been trying to get this issue resolved since November.

**Comment by alexggordon** [comment]
Hey guys, you'll be hearing from me soon over email if you purchased the plugin, but I'll be open-sourcing the plugin in the next month, along with refunding anyone that purchased it. I ended up starting a new job around December that took way more time away from this project than I ever intended, and I don't think I should have attempted to sell the plugin in the first place.

I've been in the process of making several repositories to allow for automating the mysql/postgres binary builds that are the core part of the plugin. I'm hoping to open the code base, and then move onto fixing these issues as time allows.

**Comment by nkantar** [comment]
@alexggordon Cool, good on you for following up like that. :+1:

**Comment by nkantar** [comment]
Either way this seems to be a non-issue at this point.
