### ISSUE TITLE
Can't find this package

### ISSUE THREAD

**Issue by bambang-ap** [SequoiaStudios/DB1#20]
![capture](https://cloud.githubusercontent.com/assets/18139422/20738417/8fb32824-b6e5-11e6-8e32-0e80fded0804.PNG)
Why i can't find this package? i use latest sublime text 3, hope you'll help
thanks

**Comment by alexggordon** [comment]
Currently, I'm refactoring it for AWS support and re-packing/re-releasing as open source. Should be back online in early 2017

**Comment by bambang-ap** [comment]
thanks

**Comment by RaVbaker** [comment]
still not there. @alexggordon any updates?

**Comment by quantumgolem** [comment]
@alexggordon It's mid-2017 :/
