### ISSUE TITLE
External library not found

### ISSUE THREAD

**Issue by thnt** [SequoiaStudios/DB1#7]
Installed on ST3 linux x64 but cannot start.
Console shows:
`libpython3.3m.so.1.0: cannot open shared object file: No such file or directory`
On my system package libpython3_4m1_0 was installed provides `libpython3.4m.so.1.0`

**Comment by alexggordon** [comment]
I'll have the fix for this out in about an hour. Just want to double check it on some clean versions of Ubuntu.

**Comment by alexggordon** [comment]
@thik All set now. If you run `Package Control: Upgrade Package`, select DB1, and you should be all set!
