### ISSUE TITLE
Can't find libpython2.6.so.1.0

### ISSUE THREAD

**Issue by mxcoder** [SequoiaStudios/DB1#9]
When enabling the plugin I see in the console:
libpython2.6.so.1.0: cannot open shared object file: No such file or directory

My env:

```
Distributor ID: Ubuntu
Description:    Ubuntu 15.04
Release:    15.04
Codename:   vivid

Linux {hostname} 3.19.0-31-generic #36-Ubuntu SMP Wed Oct 7 15:04:02 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Sublime Text 2 (2.0.2) Build 2221
Package Control 3.1.2
```

What I did:
- Discovered packages in PC
- Installed DB1
- Configured connections according to documentation:

```
    {
        "stored_connections": {
                "user@host1": {
                    "database_type": "MySQL",
                    "password": "password"
                },
                "user@host2": {
                    "database_type": "PostgreSQL",
                    "password": "password",
                    "port": 5439
                }
        },
        "erase_results_window": true,
        "focus_results_window_on_execution": true
    }
```
- Tried to run commands with simple SQL queries like `SELECT * FROM table LIMIT 10`

Result:
- None of the commands seems to be available
- Keyboard shortcuts doesn't work (due ^)
- Disabled and re-enabled plugin, got:

```
Reloading plugin /home/ricardoe/.config/sublime-text-2/Packages/DB1/DB1.py
libpython2.6.so.1.0: cannot open shared object file: No such file or directory
```

Googled about libpython2.6.so.1.0, seems its an old version and would require forced install of the lib (messing with a lot of other python stuff).

Let me know if you need other information.

**Comment by alexggordon** [comment]
@mxcoder Hey, so I rolled out a fix to this with Version 1.0.1. Could you run:

```
Package Control: Upgrade Package 
```

And see if DB1 is available on the list? If it is, could you upgrade and see if it's still an issue?

**Comment by mxcoder** [comment]
Hey thanks!

I think that worked for the libpython, it upgraded and now that error is gone, but now I get `No module named pymysql`.

Do you want me to resolve this one and create a new issue?

**UPDATE:**
OK. I just installed python-pymysql `apt-get install python-pymysql` and restarted ST. It works now! thank you! So far looking very good!

**Comment by alexggordon** [comment]
@mxcoder actually, installing python-pymysql shouldn't do anything. I was just going to suggest restarting Sublime Text. If you wouldn't mind, could you `apt-get remove python-pymysql`? 

Sublime Text doesn't have access to system python modules, so I think restarting Sublime was what fixed it.

**Comment by mxcoder** [comment]
You're right, just removed it, restarted it and voilá. Its working. I guess your previous fix worked I just needed to restart ST.

**Comment by alexggordon** [comment]
Perfect, glad to hear.
